# Appium
appium.server.url=http://127.0.0.1:4723

# Platform
platform.name=Android
automation.name=UiAutomator2

# Device
device.name=emulator-5554

# App
app.package=com.what3words.android
app.activity=com.what3words.android.ui.main.MainActivity
app.wait.activity=*

# Session
no.reset=false
auto.grant.permissions=true
new.command.timeout=300

# Stability
disable.window.animation=true
ignore.hidden.api.policy.error=true
